# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComposantTP4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(888, 576)
        self.mlabel = QtWidgets.QLabel(Form)
        self.mlabel.setGeometry(QtCore.QRect(30, 40, 661, 441))
        self.mlabel.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.mlabel.setText("")
        self.mlabel.setObjectName("mlabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 500, 691, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mLineEdit.setReadOnly(True)
        self.mLineEdit.setObjectName("mLineEdit")
        self.horizontalLayout.addWidget(self.mLineEdit)
        self.mBoutonBrowser = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.mBoutonBrowser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mBoutonBrowser.setAutoDefault(False)
        self.mBoutonBrowser.setDefault(False)
        self.mBoutonBrowser.setFlat(False)
        self.mBoutonBrowser.setObjectName("mBoutonBrowser")
        self.horizontalLayout.addWidget(self.mBoutonBrowser)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(710, 70, 161, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mBoutonN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mBoutonN.setObjectName("mBoutonN")
        self.verticalLayout.addWidget(self.mBoutonN)
        self.mBoutonP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mBoutonP.setEnabled(True)
        self.mBoutonP.setAcceptDrops(True)
        self.mBoutonP.setObjectName("mBoutonP")
        self.verticalLayout.addWidget(self.mBoutonP)
        self.startTimer = QtWidgets.QPushButton(Form)
        self.startTimer.setGeometry(QtCore.QRect(720, 190, 141, 23))
        self.startTimer.setCheckable(True)
        self.startTimer.setObjectName("startTimer")

        self.retranslateUi(Form)
        self.mBoutonBrowser.clicked.connect(Form.LoadFiles) # type: ignore
        self.mBoutonP.clicked.connect(Form.Previous) # type: ignore
        self.mBoutonN.clicked.connect(Form.Next) # type: ignore
        self.startTimer.clicked.connect(Form.Animate) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mLineEdit.setText(_translate("Form", "chemin vers l\'image chargée"))
        self.mBoutonBrowser.setText(_translate("Form", "..."))
        self.mBoutonN.setText(_translate("Form", "Next"))
        self.mBoutonP.setText(_translate("Form", "Previous"))
        self.startTimer.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
