# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesignerComponents/ComposantTP4_exo2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1017, 799)

        # Label pour afficher l'image
        self.mLabel = QtWidgets.QLabel(Form)
        self.mLabel.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.mLabel.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.mLabel.setText("")
        self.mLabel.setObjectName("mLabel")

        # Bouton Browse
        self.mButtonBrowse = QtWidgets.QPushButton(Form)
        self.mButtonBrowse.setGeometry(QtCore.QRect(360, 580, 81, 28))
        self.mButtonBrowse.setObjectName("mButtonBrowse")

        # Champ texte pour le chemin
        self.mLineEdit = QtWidgets.QLineEdit(Form)
        self.mLineEdit.setGeometry(QtCore.QRect(30, 580, 311, 31))
        self.mLineEdit.setObjectName("mLineEdit")

        # Boutons Next / Previous dans un vertical layout
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(720, 170, 191, 161))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.mButtonN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonN.setObjectName("mButtonN")
        self.verticalLayout.addWidget(self.mButtonN)
        self.mButtonP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonP.setObjectName("mButtonP")
        self.verticalLayout.addWidget(self.mButtonP)

        # Bouton Animate (toggle)
        self.mButtonAnimate = QtWidgets.QPushButton(Form)
        self.mButtonAnimate.setGeometry(QtCore.QRect(760, 420, 131, 28))
        self.mButtonAnimate.setCheckable(True)
        self.mButtonAnimate.setObjectName("mButtonAnimate")

        # Texte des widgets
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mButtonBrowse.setText(_translate("Form", "..."))
        self.mButtonN.setText(_translate("Form", "Next"))
        self.mButtonP.setText(_translate("Form", "Previous"))
        self.mLineEdit.setText(_translate("Form", "chemin vers l'image chargée"))
        self.mButtonAnimate.setText(_translate("Form", "START"))

# Test rapide pour vérifier le widget seul
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
