# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesignerComponents\ComposantTP4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1017, 799)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("\n"
"")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 50, 1011, 801))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(720, 170, 191, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mButtonN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonN.setObjectName("mButtonN")
        self.verticalLayout.addWidget(self.mButtonN)
        self.mButtonP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonP.setObjectName("mButtonP")
        self.verticalLayout.addWidget(self.mButtonP)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 520, 641, 151))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mLineEdit = QtWidgets.QLineEdit(self.widget)
        self.mLineEdit.setGeometry(QtCore.QRect(30, 580, 311, 31))
        self.mLineEdit.setObjectName("mLineEdit")
        self.mLabel = QtWidgets.QLabel(self.widget)
        self.mLabel.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.mLabel.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"")
        self.mLabel.setText("")
        self.mLabel.setObjectName("mLabel")
        self.mButtonBrowse = QtWidgets.QPushButton(self.widget)
        self.mButtonBrowse.setGeometry(QtCore.QRect(360, 580, 81, 28))
        self.mButtonBrowse.setObjectName("mButtonBrowse")
        self.mButtonAnimate = QtWidgets.QPushButton(self.widget)
        self.mButtonAnimate.setGeometry(QtCore.QRect(760, 420, 131, 28))
        self.mButtonAnimate.setCheckable(True)
        self.mButtonAnimate.setObjectName("mButtonAnimate")

        self.retranslateUi(Form)
        self.mButtonAnimate.clicked.connect(Form.Animate) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mButtonN.setText(_translate("Form", "Next"))
        self.mButtonP.setText(_translate("Form", "Previous"))
        self.mLineEdit.setText(_translate("Form", "chelin vers l\'image chargée"))
        self.mButtonBrowse.setText(_translate("Form", "..."))
        self.mButtonAnimate.setText(_translate("Form", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
